.gitignore
docs/cidr-ranges.md
ops/vpc.sh
tf-environments/dev/_env_defaults/main.tf
tf-environments/dev/aws/vpc/main.tf
tf-environments/dev/aws/vpc/terraform.tfvars
tf-environments/dev/terraform.tfvars
tf-environments/prod/_env_defaults/main.tf
tf-environments/prod/aws/vpc/main.tf
tf-environments/prod/aws/vpc/terraform.tfvars
tf-environments/prod/terraform.tfvars
tf-environments/qa/_env_defaults/main.tf
tf-environments/qa/aws/vpc/main.tf
tf-environments/qa/aws/vpc/terraform.tfvars
tf-environments/qa/terraform.tfvars
tf-environments/staging/_env_defaults/main.tf
tf-environments/staging/aws/vpc/main.tf
tf-environments/staging/aws/vpc/terraform.tfvars
tf-environments/staging/terraform.tfvars

Signed-off-by: garland <garlandk@gmail.com>

Adding default environments

---

clusters/aws/kops/clusters/dev-example/values.yaml
clusters/aws/kops/clusters/dev/values.yaml
clusters/aws/kops/clusters/prod/values.yaml
clusters/aws/kops/clusters/qa/values.yaml
clusters/aws/kops/clusters/staging/values.yaml
clusters/aws/kops/template/cluster.yml

Signed-off-by: garland <garlandk@gmail.com>

Adding support for a 2 zone kops configuration

---

clusters/aws/kops/clusters/dev-example/values.yaml
clusters/aws/kops/clusters/dev/values.yaml
clusters/aws/kops/clusters/prod/values.yaml
clusters/aws/kops/clusters/qa/values.yaml
clusters/aws/kops/clusters/staging/values.yaml
clusters/aws/kops/clusters/values.yaml
clusters/aws/kops/kops.sh
clusters/aws/kops/template/cluster.yml

Signed-off-by: garland <garlandk@gmail.com>

Updating kops to 1.13

---

clusters/aws/kops/clusters/ci-pipeline/values.yaml
containers/kubernetes/clusters/kops/README.md
containers/kubernetes/clusters/kops/ci-pipeline.sh
containers/kubernetes/clusters/kops/create-cluster.sh
containers/kubernetes/clusters/kops/e2e-tests.sh
containers/kubernetes/clusters/kops/setup.sh
containers/kubernetes/clusters/kops/update-cluster.sh

Creating a CI pipeline that will update a Kops Kubernetes cluster and run the sonobuoy e2e test on the cluster.

Kubernetes CI Pipeline

---

tf-modules/aws/iam/policies/source-ip-controls/main.tf
tf-modules/aws/iam/policies/source-ip-controls/outputs.tf
tf-modules/aws/iam/policies/source-ip-controls/vars.tf
tf-modules/aws/iam/policies/source-ip-controls/versions.tf

Adding AWS IAM source IP policy

---

containers/kubernetes/clusters/kops/README.md
containers/kubernetes/clusters/kops/setup.sh
containers/kubernetes/clusters/kops/update-cluster.sh

Fixing bugs

---

kubernetes/helm/http-echo/deployment.yaml
tf-modules/gcp/nodepool/main.tf
tf-modules/gcp/private-gke-cluster/main.tf
tf-modules/gcp/vpc/main.tf
tf-modules/gcp/vpc/vars.tf

Moving backend store to GCP from S3 for the GCP items

---

tf-environments/gcp/README.md
tf-environments/gcp/dev/dev/cluster/terragrunt.hcl
tf-environments/gcp/dev/dev/networking/terragrunt.hcl
tf-environments/gcp/dev/dev/nodepools/pool-1/terragrunt.hcl
tf-environments/gcp/dev/dev/nodepools/pool-2/terragrunt.hcl
tf-environments/gcp/dev/terragrunt.hcl

Re-organizing the GCP dev env so that it is easier to use.

GCP - dev env re-organization

---

docs/README.md
docs/accessing-private-vpc-from-ci-system.md
docs/cidr-ranges.md
docs/github-actions.md
docs/kubernetes-security/README.md
docs/the-easier-way.md
docs/the-manual-way.md
docs/tools.md

While reading all the documentation and going through the steps for learning purposes fixed up some of the grammar.

Grammar pass

---

tf-environments/gcp/dev/_env_defaults/gcp.tfvars
tf-environments/gcp/dev/nodepools/pool-1/terragrunt.hcl
tf-modules/gcp/nodepool/main.tf
tf-modules/gcp/nodepool/vars.tf
tf-modules/gcp/private-gke-cluster/main.tf
tf-modules/gcp/private-gke-cluster/vars.tf

Adding in feature to specify a regional or zonal GKE cluster type

---

kubernetes/flux/namespaces/sealed-secrets.yaml
kubernetes/flux/releases/gcp/dev/nginx-ingress/internal.yaml
kubernetes/flux/releases/gcp/dev/prometheus-operator/prometheus-operator.yaml
kubernetes/flux/releases/gcp/dev/sealed-secrets/sealed-secrets.yaml
kubernetes/helm/flux/flux/environments/dev/values.yaml
kubernetes/helm/sealed-secrets/README.md

Adding the Bitnami sealed-secrets helm chart.

sealed-secrets Helm chart

---

kubernetes/flux/releases/gcp/dev/sealed-secrets/sealed-secrets.yaml

Updating sealed secrets to v1.8.0

---

kubernetes/flux/namespaces/external-dns.yaml

Adding external-dns namespace

---

kubernetes/flux/releases/gcp/dev/external-dns/helmrelease.yaml

Updating with the correct namespace

---

kubernetes/flux/releases/gcp/dev/external-dns/helmrelease.yaml
kubernetes/flux/releases/gcp/dev/prometheus-operator/helmrelease.yaml

Updating the values.yaml path

---

kubernetes/flux/releases/gcp/dev/nginx-ingress/helmrelease-external.yaml
kubernetes/flux/releases/gcp/dev/prometheus-operator/values.yaml

Updating prom to go to the external ingress

---

kubernetes/flux/releases/gcp/dev/nginx-ingress/helmrelease-external.yaml

Updating the ingress to name it external

---

.github/workflows/terraform.yml
.github/workflows/test-workflow.yaml
main.tf

Adding testing tf files

---

.github/workflows/terraform-tutorial-pipeline.yml

Commenting out

---

.github/workflows/terraform-vpc.yaml
terraform-environments/aws/dev/vpc/main.tf

Renaming workflow

---

terraform-environments/aws/dev/vpc/main.tf

Updating workspace name

---

terraform-environments/aws/dev/vpc/main.tf

Addig vpc output

---

terraform-environments/aws/dev/main.tf

Updating versions

---

terraform-modules/aws/eks/eks.tf
terraform-modules/aws/eks/variables.tf

Ran terraform fmt

---

terraform-environments/aws/dev/main.tf

Bumping the version

---

terraform-environments/aws/dev/main.tf
terraform-modules/aws/helm/argocd/outputs.tf
terraform-modules/aws/helm/nginx-ingress/outputs.tf

Adding nginx-ingress

---

terraform-modules/aws/helm/kube-prometheus-stack/README.md
terraform-modules/aws/helm/kube-prometheus-stack/main.tf
terraform-modules/aws/helm/kube-prometheus-stack/outputs.tf
terraform-modules/aws/helm/kube-prometheus-stack/values.yaml
terraform-modules/aws/helm/kube-prometheus-stack/variables.tf

Adding prometheus module

---

terraform-environments/aws/dev/main.tf

Adding prometheus

---

.github/workflows/terraform-pipeline.yaml

Changing branch name to main

---

terraform-environments/aws/dev/main.tf

minor change to kick the pipeline to run

---

terraform-modules/aws/helm/kube-prometheus-stack/values.yaml
terraform-modules/aws/vpc/main.tf
terraform-modules/aws/vpc/variables.tf

Adding subnet tags for the kube elbs

---

terraform-environments/aws/dev/main.tf

Updating vpc with cluster name

---

terraform-environments/aws/dev/helm_values/kube-prometheus-stack/values.yaml

Removing yaml field

---

terraform-modules/aws/helm/helm_generic/README.md
terraform-modules/aws/helm/helm_generic/main.tf
terraform-modules/aws/helm/helm_generic/outputs.tf
terraform-modules/aws/helm/helm_generic/variables.tf

Adding helm generic module

---

terraform-environments/aws/dev/main.tf

Updating helm module version

---

terraform-modules/aws/helm/kube-prometheus-stack/values.yaml

Updating default value

---

terraform-environments/aws/dev/main.tf
terraform-modules/aws/eks/eks.tf

Increasing to 2 nodes

---

terraform-environments/aws/dev/main.tf

Updating module that supports tf 0.15

---

terraform-environments/aws/dev/main.tf

Updating the var name

---

terraform-environments/aws/dev/main.tf

updating eks usage

---

terraform-environments/aws/dev/main.tf

Updating vpc usage

---

terraform-environments/aws/staging/10-vpc/main.tf
terraform-environments/aws/staging/10-vpc/outputs.tf
terraform-environments/aws/staging/20-eks/README.md
terraform-environments/aws/staging/20-eks/main.tf
terraform-environments/aws/staging/20-eks/outputs.tf
terraform-environments/aws/staging/25-eks-cluster-autoscaler/main.tf
terraform-environments/aws/staging/5-route53-hostedzone/main.tf
terraform-environments/aws/staging/5-route53-hostedzone/outputs.tf
terraform-environments/aws/staging/helm/cert-manager/helm_values.yaml
terraform-environments/aws/staging/helm/cert-manager/main.tf
terraform-environments/aws/staging/helm/external-dns/README.md
terraform-environments/aws/staging/helm/external-dns/main.tf
terraform-environments/aws/staging/helm/external-dns/values.yaml
terraform-environments/aws/staging/helm/grafana-loki/README.md
terraform-environments/aws/staging/helm/grafana-loki/main.tf
terraform-environments/aws/staging/helm/grafana-loki/values.yaml
terraform-environments/aws/staging/helm/ingress-nginx-external/README.md
terraform-environments/aws/staging/helm/ingress-nginx-external/main.tf
terraform-environments/aws/staging/helm/kube-prometheus-stack/README.md
terraform-environments/aws/staging/helm/kube-prometheus-stack/main.tf
terraform-environments/aws/staging/helm/kube-prometheus-stack/values.yaml
terraform-environments/aws/staging/helm/sample-app/helm_values.yaml
terraform-environments/aws/staging/helm/sample-app/main.tf
terraform-environments/aws/staging/helm/sample-app/variables.tf

This is the code used for demos in the "Getting Started with EKS" course on Pluralsight.com where a complete staging environment is set up and a sample docker app deployed with custom DNS, https ingress, and HPA enabled.

samples to set up staging environment

---

terraform-environments/aws/staging/README.md

Added link to video course that walks through the entire setup.
@sekka1 after this commit is merged please create a tag named `eks-getting-started`

README for staging example

---

terraform-modules/aws/s3_bucket/main.tf

Letting the instantiator to define it

Removing provider

---

terraform-modules/aws/helm/istio-kiali/main.tf
terraform-modules/aws/helm/istio-kiali/values.yaml
terraform-modules/aws/helm/istio-kiali/variables.tf
terraform-modules/aws/helm/kube-prometheus-stack/README.md
terraform-modules/aws/helm/kube-prometheus-stack/values.yaml
terraform-modules/aws/helm/kube-prometheus-stack/variables.tf
terraform-modules/aws/kubernetes/manifest/main.tf
terraform-modules/aws/kubernetes/manifest/variables.tf

* Updating kube prom stack
* Istio Kiali

Kube prom stack 33.2.0

---

terraform-environments/aws/terragrunt-dev/README.md
terraform-environments/aws/terragrunt-dev/common.hcl
terraform-environments/aws/terragrunt-dev/terragrunt.hcl
terraform-environments/aws/terragrunt-dev/us-east-1/region.hcl
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/050-github-aws-permissions/.terraform.lock.hcl
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/050-github-aws-permissions/README.md
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/050-github-aws-permissions/policy.json
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/050-github-aws-permissions/terragrunt.hcl
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/environment.hcl

Adding the new `terragrunt-dev` environment.

terragrunt-dev environment

---

.github/workflows/terragrunt-dev.yaml
terraform-environments/aws/terragrunt-dev/README.md
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/100-vpc/terragrunt.hcl

* Adding Github Action Terragrunt pipeline file
* Adding VPC instantiation into terragrunt-dev

Terragrunt-dev - vpc

---

.github/workflows/terragrunt-dev.yaml
.gitignore
terraform-environments/aws/terragrunt-dev/provider_k8s_helm_for_eks.template.hcl
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/250-eks-cluster-autoscaler/.terraform.lock.hcl
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/250-eks-cluster-autoscaler/terragrunt.hcl

* Clusterautoscaler
* EKS/Helm terraform provider

Cluster autoscaler

---

.github/workflows/terragrunt-dev.yaml
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/300-kubernetes/110-testkube/20-infra-base/terragrunt.hcl
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/300-kubernetes/200-istio/10-istio/terragrunt.hcl
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/300-kubernetes/200-istio/40-istio-kiali/terragrunt.hcl

* Upgrading istio to 1.14.3
* Upgrading kiali to the latest version that support this istio version
* Updating the testkube prometheus check to be more generic
* Updating testkube with the dockerfile fix and enabling it again

istio-upgrade-1.14.x

---

.github/workflows/terragrunt-dev.yaml
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/300-kubernetes/110-testkube/20-infra-base/terragrunt.hcl
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/300-kubernetes/200-istio/10-istio/terragrunt.hcl
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/300-kubernetes/200-istio/40-istio-kiali/terragrunt.hcl

Reverts ManagedKube/kubernetes-ops#371

Revert "istio-upgrade-1.14.x"

---

.github/workflows/terragrunt-dev.yaml
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/300-kubernetes/110-testkube/20-infra-base/terragrunt.hcl
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/300-kubernetes/200-istio/10-istio/terragrunt.hcl
terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/300-kubernetes/200-istio/40-istio-kiali/terragrunt.hcl

* Upgrading istio to 1.14.3
* Upgrading kiali to the latest version that support this istio version
* Updating the testkube prometheus check to be more generic
* Updating testkube with the dockerfile fix and enabling it again

Istio upgrade 1.14.x

---

terraform-modules/azure/aks/cluster2/main.tf
terraform-modules/azure/aks/cluster2/variables.tf
terraform-modules/azure/aks/node_pool/main.tf
terraform-modules/azure/aks/node_pool/vars.tf

Adding agents_availability_zones param

AKS Avail Zones param

---

terraform-environments/azure/dev/east-us-2/dev/20-aks/10-cluster/terragrunt.hcl
terraform-modules/azure/aks/README.md
terraform-modules/azure/aks/cluster2/main.tf
terraform-modules/azure/aks/cluster2/variables.tf

* Updates the module to using version 6.6.0
* Adds the Azure Active DIrectory options
* Adding option for the default admin group creation or input

Aks update

---

terraform-environments/azure/dev/east-us-2/dev/20-aks/10-cluster/terragrunt.hcl
terraform-modules/azure/container_registry/main.tf
terraform-modules/azure/container_registry/variables.tf
terraform-modules/azure/vault/main.tf
terraform-modules/azure/vault/variables.tf

* Azure container registry module
* Azure vault `purge_protection_enabled` input var option

Azure container registry

---

terraform-environments/azure/dev/east-us-2/dev/20-aks/10-cluster/terragrunt.hcl
terraform-modules/azure/vault-access/README.md
terraform-modules/azure/vault-access/main.tf
terraform-modules/azure/vault-access/outputs.tf
terraform-modules/azure/vault-access/variables.tf

* A module to access access policies to an Azure Vault instance

Azure vault access

---

terraform-environments/azure/dev/east-us-2/dev/20-aks/10-cluster/terragrunt.hcl
terraform-modules/azure/kubernetes/external-secrets/secret_store/main.tf
terraform-modules/azure/kubernetes/external-secrets/secret_store/variables.tf

* Parameterizes the Azure Vault Access Policies

Az external secrets permissions

---

README.md
terraform-modules/aws/s3/bucket/README.md
terraform-modules/aws/s3/bucket/main.tf
terraform-modules/aws/s3/bucket/variables.tf

- Being this module able to receive s3 bucket ownership controls rule as input variable.
- Sometimes some resources like kafka msk needs other kind of rules to work . 
- Where I am testing this branch 
https://github.com/exact-payments/gruntwork-infrastructure-live/pull/1533/files#diff-65d38f80970bf9400bbec4ae7cddab572f214465fdc6c6d6b93306af1ed7b56bR12
- inputs
bucket_ownership_controls_rule = "BucketOwnerPreferred"
```
inputs = {
aws_region              = local.aws_region
bucket                  = local.bucket_name
acl                     = "private"
block_public_acls       = false
block_public_policy     = true
ignore_public_acls      = true
restrict_public_buckets = true
policy                  = templatefile(
"./policy.json",
{
bucket_name    = local.bucket_name
aws_region     = …
```

S3 bucket ownership controls rule

---

README.md
terraform-modules/aws/s3/bucket/README.md

I screwed up and delete read me in #420 
this pr is recovering original readme and add it that I want to add in s3 bucket , new properties.

Recover readme and add more field in s3 bucket

---

terraform-modules/aws/helm/helm_generic/README.md
terraform-modules/aws/helm/helm_generic/main.tf
terraform-modules/aws/helm/helm_generic/outputs.tf
terraform-modules/aws/helm/helm_generic/variables.tf

* Adding all available terraform options

Helm Generic - All options
