ManagedKube/kubernetes-ops

tf-modules/aws/rds/vars.tf
The type needs to be set here to be able to properly override the variable from terragrunt or a TF_VAR envvar.
=> setting engine_version type to map(string)

terraform-modules/aws/eks/variables.tf
Variables of non-string types can cause issues with tools like terragrunt (e.g. https://github.com/gruntwork-io/terragrunt/issues/1007) if the type is not explicitly defined when the variable is declared in the module.
This pull request adds a type to the `tags` variable in the eks module, making it consistent with the vpc, istio, and other modules in this repo.
=> Cleaning up variables.tf file for eks module

terraform-modules/aws/vpc/outputs.tf
- Obtains a list of routing table ids on public subnets and another for private subnets.
- Name of vpc 
**_Necessity_**: 
It is necessary to perform peerings between vpcs and get the auto-generated route table ids.
_**Reference documentation**_
[private_route_table_ids](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/2.77.0?tab=outputs#:~:text=private_route_table_ids
)
[public_route_table_ids](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/2.77.0?tab=outputs#:~:text=public_route_table_ids)
[name of vpc](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/2.77.0?tab=outputs#:~:text=IPv6%20enabled%20VPC-,name,-Description%3A%20The%20name)
=> output vars for route table ids public and privates subnets and name of vpc

terraform-modules/aws/vpc/outputs.tf
- Obtains a list of secondary CIDRs of vpc  
_**Reference documentation**_
[vpc_secondary_cidr_blocks](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest?tab=outputs#:~:text=vpc_secondary_cidr_blocks
)
=> add secondary cidr_blocks as output var in vpc mod

terraform-modules/aws/mongodb-atlas-users/main.tf, terraform-modules/aws/mongodb-atlas-users/variables.tf
Due to limitations of current MongoDB drivers (see https://jira.mongodb.org/browse/DRIVERS-2011), assuming an arbitrary AWS IAM role is not feasible in many situations.
In those cases, a workaround is to create an additional user in MongoDB based on the role being assumed by the driver.
=> Adding an optional custom user for Mongo Atlas

terraform-modules/aws/eks/outputs.tf
The ARN of the worker IAM role created by this module is needed, for example, when [setting up a user for Mongo Atlas](https://github.com/ManagedKube/kubernetes-ops/pull/249).
=> Exposing IAM Role ARNs as outputs of the EKS module

terraform-modules/aws/istio-networking/main-gateway/gateway.tpl.yaml, terraform-modules/aws/istio-networking/main-gateway/main.tf, terraform-modules/aws/istio-networking/main-gateway/variables.tf
This component is enabled to:
1. Create the certificate on demand through the variable: [enable_certificate](https://github.com/ManagedKube/kubernetes-ops/blob/472841123906bae9f6c2d8c67938566993460d9e/terraform-modules/aws/istio-networking/main-gateway/variables.tf#L32). 
2. New input parameter [gateway_hosts](https://github.com/ManagedKube/kubernetes-ops/pull/255/files#:~:text=host%3A%20%24%7Bgateway_hosts%7D)
3. New input parameter [gateway_credentialName](https://github.com/ManagedKube/kubernetes-ops/pull/255/files#:~:text=credentialName%3A%20%24%7Bgateway_credentialName%7D)   
A plan was made locally, reflecting the resulting yaml files.
Input vars:
```
variable "gateway_hosts" {
type    = list(string)
description = "the list of hosts available for the gateway"
default = …
```
=> Certificate on-demand in istio-gateway and new input params gateway hosts and credentialName

terraform-modules/aws/istio-networking/main-gateway/variables.tf
In order to turn off the use of the certificate, it is necessary to define this vars the cert_common_name variables and
cert_dns_name as no required values for avoiding assignments empty on users side. 
```
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 22:
│   22: variable "cert_common_name" {
│ 
│ The root module input variable "cert_common_name" is not set, and has no
│ default value. Use a -var or -var-file command line argument to provide a
│ value for this variable.
╵
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 27:
│   27: variable "cert_dns_name" {
│ 
│ The root module input variable "cert_dns_name" is not set, and has no
│ default value. Use a -var or -var-file command line argument to provide a
│ value for this variable.
╵
```
=> Default values cert_common_name and cert_dns_name

terraform-modules/aws/istio-networking/main-gateway/gateway.tpl.yaml
Bugfix 
Syntax error in module main-gateway, replace host with hosts.
=> sintaxs error: replace host with hosts

terraform-modules/aws/helm/external-secrets/install/helm_values.tpl.yaml, terraform-modules/aws/helm/external-secrets/install/main.tf, terraform-modules/aws/helm/external-secrets/install/variables.tf
Implements a new input variable called `account_id` in order to mitigate an issue found in aws_caller_id, which instead of getting the aws `account number` like: `54518548741` of the currently calling process, it's getting `***`
**_Testing:_**
- When the user does not pass the account_id variable, the aws_caller_id is executed.
`awsAccountID  = var.account_id != null ? var.account_id : data.aws_caller_identity.current.account_id`
- When the user pass a value in account_id variable
`awsAccountID  = var.account_id != null ? var.account_id : data.aws_caller_identity.current.account_id`
=> New input var account_id

terraform-modules/aws/mongodb-atlas-user-list/main.tf, terraform-modules/aws/mongodb-atlas-user-list/variables.tf
Enable the component: `terraform-modules/aws/mongodb-atlas-user-list` which is turned on or off with the variable: `enable_percent_encoding_password`.
This enables the component to store the password in aws secret manager in percent-encoding mode; this in order to escape characters that damage the mongodb connection string.
**Documentation**:
https://www.mongodb.com/docs/manual/reference/connection-string/#examples
Bad strings: `: / ? # [ ] @`
**Testing**: 
`enable_percent_encoding_password` = true
=> Enable percent encoding password

terraform-modules/aws/mongodb-atlas-alerts/variables.tf
Removing alerts that are not able to be applied.  It returns an error when trying to apply.
=> Mongo default alerts

.github/workflows/terragrunt-dev.yaml, terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/300-kubernetes/10-cert-manager/.terraform.lock.hcl, terraform-environments/aws/terragrunt-dev/us-east-1/terragrunt-dev/300-kubernetes/10-cert-manager/terragrunt.hcl, terraform-modules/aws/helm/cert-manager/main.tf
The `kubectl_manifest` terraform resource is a third party module that applies kubernetes yaml.  Switching over the usage to the hashicorp module that does the same thing `kubernetes_manifest`.  It will be less headache going forward using the first party module and have to pull in less stuff.
=> Cert Manager Update

terraform-modules/aws/vpc/main.tf, terraform-modules/aws/vpc/variables.tf
When creating a `VPC`, the module also creates a default security group; this module will continue to create it but in a secure way.
- Allows all outbound traffic rules
- Allows RFC1918 and rfc6598 in inbouand traffic rules
=> CR-150 Security Group Default Management

terraform-modules/aws/kubernetes/pod_assumable_role/main.tf, terraform-modules/aws/kubernetes/pod_assumable_role/variables.tf
- Add a new array field to associate more than once policy. (readonly policies)
```
variable "iam_policy_arns" {
type        = list(string)
description = "The IAM policy readonly list"
default     = []
}
```
- Concat the list with json file
`role_policy_arns              = concat(var.iam_policy_arns, [aws_iam_policy.iam_policy.arn])`
**Evidence of proof**
- The following is a test where the new field : iam_policy_arns was sent empty and the result was that it only assigned the json policy. This means that there is compatibility with existing implementations. (This is because the defult of the new field is [].)
- The following is a test sending 2 readonly policies plus the json file, and the result was 3 policies.
=> Feat: pod assumable arns policy list 

terraform-modules/aws/s3_bucket/main.tf, terraform-modules/aws/s3_bucket/variables.tf
The AWS S3 bucket Terraform resources has been splitting up the bucket configuration composition into different resources.  The usage in here was deprecated and this PR updates all of the deprecated items to use the newer items.  It is backwards compatible.
=> Aws s3 encrypt update

terraform-modules/aws/s3_bucket/main.tf
The AWS S3 bucket Terraform resources has been splitting up the bucket configuration composition into different resources. The usage in here was deprecated and this PR updates all of the deprecated items to use the newer items. It is backwards compatible.
=> aws-s3-encrypt-update-2

terraform-modules/aws/eks/main.tf, terraform-modules/aws/eks/variables.tf
Prior to this, the AWS EKS module said it shouldnt handle the kubernetes auth configmap which means that the user of this module has to do it on their own.  Which we did.  It now looks like they have reverted that stance and the module manages the auth config map again.  We are reverting our usage back to this.
=> EKS - Auth - Back to regular auth config map usage

terraform-modules/aws/eks/main.tf, terraform-modules/aws/eks/variables.tf
**Context**
EKS cluster has a KMS key, the enabled rotation default of the flag is false
**What does this do?** 
-  add a new env var called: cluster_kms_enable_rotation pointing to the module: 
When you enable automatic key rotation for a KMS key, AWS KMS generates new cryptographic material for the KMS key every year. AWS KMS saves all previous versions of the cryptographic material in perpetuity so you can decrypt any data encrypted with that KMS key. AWS KMS does not delete any rotated key material until you [delete the KMS key](https://docs.aws.amazon.com/kms/latest/developerguide/deleting-keys.html). You can [track the rotation](https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html#monitor-key-rotation) of key material for your KMS keys in Amazon CloudWatch and AWS …
=> enabled rotation for kms eks cluster

terraform-modules/aws/s3_bucket/main.tf, terraform-modules/aws/s3_bucket/variables.tf
**feat**: add bucket-owner-enforce s3
**what solves this?**
Security scanners such as [prowler](https://github.com/prowler-cloud/prowler) report this vulnerability with s3 buckets created with this module.
`Bucket name has bucket ACLs enabled!`
**how does it do it?**
Creates a new resource on demand 
```
resource "aws_s3_bucket_ownership_controls" "bucket_ownership_controls" {
count = var.enable_bucket_owner_enforced ? 1 : 0
bucket = aws_s3_bucket.bucket.id
rule {
object_ownership = "BucketOwnerEnforced"
}
}
```
**What is the result?**
- Plan:
```
plan. Resource actions are indicated with the following symbols:
+ create
+ resource "aws_s3_bucket_ownership_controls" "bucket_ownership_controls" {
+ bucket = "476264532441-x2-ops-prowler"
+ id …
```
=> Feat bucket-owner-enforce s3

terraform-modules/aws/eks/variables.tf
- Some solutions to scan vulnerabilities like [prowler](https://github.com/prowler-cloud/prowler) reports the following:
- Eks ManagedKube module has 90 days like default in log group cloud watch.
https://github.com/ManagedKube/kubernetes-ops/blob/b8f16f1434a7af52d2bbebbb818eaad7a6274f8d/terraform-modules/aws/eks/variables.tf#L131-L135
- Set as default 365 days cloud watch log groups retentions
https://github.com/ManagedKube/kubernetes-ops/blob/8bb756ef66a4235bd37f895b70ab613079bdfd6e/terraform-modules/aws/eks/variables.tf#L131-L135
```
~ resource "aws_cloudwatch_log_group" "this" {
id                = "/aws/eks/ops/cluster"
name              = "/aws/eks/ops/cluster"
~retention_in_days = 90 ->365
tags              = {
"ops_env"              = "ops"
"ops_managed_by"       = "terraform" …
```
=> Change 365 by default in retention days in cloudwatch 

terraform-modules/aws/cloudposse/aws-cloudtrail-cloudwatch-alarms/main.tf
- Add kms to cloud watch log group.
```
+ resource "aws_kms_key" "kms" {
+ arn                                = (known after apply)
+ bypass_policy_lockout_safety_check = false
+ customer_master_key_spec           = "SYMMETRIC_DEFAULT"
+ deletion_window_in_days            = 10
+ description                        = "KMS key for x2-ops-cloudtrail-cloudwatch-alarms"
+ enable_key_rotation                = true
+ id                                 = (known after apply)
+ is_enabled                         = true
+ key_id                             = (known after apply)
+ key_usage                          = "ENCRYPT_DECRYPT"
+ multi_region                       = (known after apply)
+ policy                             = jsonencode(
{
+ Statement = [
+ {
+ Action    = [
+ "kms:Update*",
+ …
```
=> Add Kms to cloudposse in cloud-trail-watch-alarms

terraform-modules/aws/eks/main.tf, terraform-modules/aws/kms/cloudwatch_log_group/README.md, terraform-modules/aws/kms/cloudwatch_log_group/main.tf, terraform-modules/aws/kms/cloudwatch_log_group/outputs.tf, terraform-modules/aws/kms/cloudwatch_log_group/variables.tf
- Create a new module called kms/cloudwatch_log_group: https://github.com/ManagedKube/kubernetes-ops/blob/571db96641b25483de84fdde4491401d4d0107c7/terraform-modules/aws/eks/main.tf#L35-L39
- This module is consuming by eks to asociate an standard kms for log groups.
- One of the advantages is that this module can be used for future components that need cloudwatch log groups and wish to associate a kms that will free them from vulnerabilities.
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
~ update in-place
~ resource "aws_cloudwatch_log_group" "this" {
id                = "/aws/eks/ops/cluster"
+ kms_key_id        = (known after apply)
name …
```
=> Add kms to eks cloudwatch log group

terraform-modules/aws/vpc/variables.tf
- Change default_security_group_egress default by rfc ips instead of 0.0.0.0
```
~ resource "aws_default_security_group" "this" {
~ egress                 = [
+ {
+ cidr_blocks      = [
+ "10.0.0.0/8",
]
+ description      = "rfc1918: Private Address Space"
+ from_port        = 0
+ ipv6_cidr_blocks = []
+ prefix_list_ids  = []
+ protocol         = "-1"
+ security_groups  = []
+ self             = false
+ to_port          = 0
},
+ {
+ cidr_blocks      = [
+ "100.64.0.0/10",
]
+ description      = "rfc6598: Private Address Space"
+ from_port        = 0
+ ipv6_cidr_blocks = []
+ prefix_list_ids  = []
+ protocol         = "-1"
+ security_groups  = []
+ self             = false
+ to_port          = 0
},
+ {
+ cidr_blocks      = [
+ "172.16.0.0/12", …
```
=> rfc1918 and rfc6598 in default_security_group_egress

terraform-modules/aws/cloudposse/aws-cloudtrail-cloudwatch-alarms/main.tf
Need to merge this pr and generate the v2.0.41 version 
Because version 2.0.39 does not have the kms trail changes.
https://github.com/ManagedKube/kubernetes-ops/blob/6124ac58ac389e233701bc1fcf6ee2f47c89ae22/terraform-modules/aws/cloudposse/aws-cloudtrail-cloudwatch-alarms/main.tf#L6-L16
=> fix kms version v2.0.40

terraform-modules/aws/testkube/base-tests/test-suites/infra-base/yaml/prometheus-endpoint.yaml
The output for the newest version of the prometheus included in the kube-prometheus-stack for the health check has changed (argg!!!).  Updating the text response to be more generic.  This change is backwards compatible with older prometheus versions as well.
```
kubectl -n istio-system exec -it istio-ingressgateway-6d7b845966-cn44n -- bash
istio-proxy@istio-ingressgateway-6d7b845966-cn44n:/$ curl
curl: try 'curl --help' or 'curl --manual' for more information
istio-proxy@istio-ingressgateway-6d7b845966-cn44n:/$ curl -v http://prometheus-operated.monitoring.svc:9090/-/ready
*   Trying 10.117.195.25:9090...
* TCP_NODELAY set
* Connected to prometheus-operated.monitoring.svc (10.117.195.25) port 9090 (#0)
> GET /-/ready HTTP/1.1
> Host: prometheus-operated.monitoring.svc:9090
> User-Agent: …
```
=> Editing expected response for testkube

terraform-modules/aws/iam/generic/README.md, terraform-modules/aws/iam/generic/main.tf, terraform-modules/aws/iam/generic/outputs.tf, terraform-modules/aws/iam/generic/variables.tf
The IAM role is a important aws component regards to security; We din't have a module to create IAM Role in a generic way, We only have modules to IAM with specific task like pod assumble role or pipelines stuffs, the currently module is trying to be generic.
- force detaching any policies the role has before destroying it
- able to set maximum session duration
- 1 Inline policy
- 1 or N managed policies Arns
- 1 Assumed policy
- Tags for identifying the resource
| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| <a name="input_iam_assume_role_policy"></a> [iam\_assume\_role\_policy](#input\_iam\_assume\_role\_policy) | Json to create assume\_role\_policy in line | `string` | `"{}"` | no |
| <a name="input_iam_description"></a> …
=> IAM generic module

terraform-modules/aws/eks/main.tf, terraform-modules/aws/eks/variables.tf
We upgraded to eks 1.23 recently but we have an issue regards to volumens
error
```
Warning  FailedMount         31m (x5 over 63m)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[prometheus-kube-prometheus-stack-prometheus-db], unattached volumes=[prometheus-kube-prometheus-stack-prometheus-db web-config config config-out prometheus-kube-prometheus-stack-prometheus-rulefiles-0 kube-api-access-4dcz8 tls-assets]: timed out waiting for the condition
Warning  FailedMount         27m (x2 over 38m)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[prometheus-kube-prometheus-stack-prometheus-db], unattached volumes=[config config-out prometheus-kube-prometheus-stack-prometheus-rulefiles-0 kube-api-access-4dcz8 tls-assets …
```
=> EKS 1.23 cis driver compatibility

terraform-modules/aws/securitygroup/README.md, terraform-modules/aws/securitygroup/main.tf, terraform-modules/aws/securitygroup/outputs.tf, terraform-modules/aws/securitygroup/variables.tf
- Create security groups with dynamic egress and ingress rules.
I am using this branch in https://github.com/exact-payments/gruntwork-infrastructure-live/pull/1523/files#diff-e91895dc3db4c983ccee4507ad3193f15ce0dae981239cefb1d7118e3527312cR12 \
- inputs
```
Inputs = {
vpc_id        = dependency.vpc.outputs.vpc_id
name          = local.name
description   = local.description
ingress_rules = [
{
description      = "Allow SSH to vpc mainly CIDR"
from_port        = 22
to_port          = 22
protocol         = "tcp"
cidr_blocks      = ["${local.vpc_cidr}"]
ipv6_cidr_blocks = []
},
{
description      = "Allow SSH to vpc secondary CIDR"
from_port        = 443
to_port          = 443
protocol         = "tcp"
cidr_blocks      = ["${local.vpc_secondary_cidr}"]
ipv6_cidr_blocks = []
}
]
egress_rules = …
```
=> AWS Security group in managedkube

terraform-modules/aws/airflow/main.tf, terraform-modules/aws/airflow/variables.tf
- The webserver_access_mode variable was added to the aws_mwaa_environment resource block, allowing for more control over the web server's access mode.
- The IAM role module was updated to the latest version (5.11.2) to incorporate bug fixes and other improvements.
- The aws_s3_bucket resource creates an S3 bucket, which is used as the source for the MWAA environment. The aws_s3_bucket_versioning resource enables versioning for the S3 bucket. The aws_s3_bucket_acl resource sets the bucket ACL to private, which means that only authorized users can access the bucket.
- The aws_s3_bucket_server_side_encryption_configuration resource enables server-side encryption for the S3 bucket. The aws_s3_bucket_public_access_block resource blocks public access to the S3 bucket.
```
inputs = { …
```
=> Update Airflow Module

terraform-modules/aws/qldb/main.tf, terraform-modules/aws/qldb/outputs.tf, terraform-modules/aws/qldb/variables.tf
**This PR adds a deployment of Amazon Web Services' Quantum Ledger Database (QLDB) with a VPC endpoint. The following changes have been made to the Terraform configuration:** 
- Added an AWS QLDB ledger resource with the specified name and permissions mode, and with deletion protection enabled to prevent accidental deletion of the ledger.
- Added a security group resource with the specified name and description, and allowing TLS traffic from the VPC and all egress traffic.
- Added an AWS VPC endpoint resource with the QLDB service name, endpoint type and attached to the security group resource. This allows QLDB clients to access the QLDB service using a private IP address within the VPC, without requiring a public IP address or internet gateway.
By deploying QLDB with a VPC endpoint, we …
=> Update qldb module

terraform-modules/aws/secret-manager/README.md, terraform-modules/aws/secret-manager/main.tf, terraform-modules/aws/secret-manager/outputs.tf, terraform-modules/aws/secret-manager/variables.tf
Creates a modules to new aws secret manager + kms
84-6e218ef9-4b69-4737-83e5-de5e0e323ffa.png)
```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
+ resource "aws_kms_key" "this" {
+ arn                                = (known after apply)
+ bypass_policy_lockout_safety_check = false
+ customer_master_key_spec           = "SYMMETRIC_DEFAULT"
+ deletion_window_in_days            = 30
+ description                        = "AmazonMSK_dp-dev-kafka-user-kms"
+ enable_key_rotation                = false
+ id                                 = (known after apply)
+ is_enabled                         = true
+ key_id                             = (known …
```
=> Secret manager module + kms

terraform-modules/aws/iam/generic/README.md, terraform-modules/aws/iam/generic/main.tf, terraform-modules/aws/iam/generic/outputs.tf, terraform-modules/aws/iam/generic/variables.tf
This is pr has the opportunity to add to IAM generic module turn on in a IAM instances profile
Resources like EMR needs instances profile
you need to create IAM as normal way + create_iam_instance_profile = true
https://github.com/exact-payments/gruntwork-infrastructure-live/pull/1608/files#diff-b46dfee18bf3e8a7b120fd1adaadc40ee2c8af9f3f8bae1d7dacf7a514f6ccb6R12 
```
Acquiring state lock. This may take a few moments...
aws_iam_role.this: Refreshing state... [id=dp-dev-emr-ec2-role]
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
+ resource "aws_iam_instance_profile" "this" {
+ arn         = (known after apply)
+ create_date = (known after apply) …
```
=> iam instance profile

terraform-modules/aws/airflow/README.md, terraform-modules/aws/airflow/main.tf, terraform-modules/aws/airflow/variables.tf
I am incrementing functionality to Airflow terraform in managed kube adding three news environment variables such as
```
variable "iam_extra_policies" {
description = "List of additional policies to create and attach to the IAM role"
type        = list(object({
name_prefix = string
policy_json = string
}))
default     = []
}
variable "sg_extra_ids" {
description = "List of additional sg to create and attach to Airflow"
type        = list(string)
default     = []
}
variable "requirements_s3_path" {
description = "The S3 path for the MWAA requirements file."
type        = string
default     = ""
}
```
Here's a human explanation of these variables:
iam_extra_policies:
This variable is for a list of additional policies that you want to create and attach to an Identity and Access Management …
=> Airflow Extra Policy + Extra Sgs

terraform-modules/aws/airflow/README.md, terraform-modules/aws/airflow/default_iam_policy.json
- We have been some issues in airflow 
- This fix in the policy help us to overcome
```
*** Reading remote log from Cloudwatch log_group: airflow-dp-dev-airflow-Task log_stream: dag_id=elevon_data_kafka_ingestion_test/run_id=manual__2023-04-25T00_53_37.904648+00_00/task_id=elevon_data_kafka_ingestion_test/attempt=1.log.
Could not read remote logs from log_group: airflow-dp-dev-airflow-Task log_stream: dag_id=elevon_data_kafka_ingestion_test/run_id=manual__2023-04-25T00_53_37.904648+00_00/task_id=elevon_data_kafka_ingestion_test/attempt=1.log.
```
=> Bugfix over airflow deafult policy

terraform-modules/aws/helm/helm_generic/main.tf, terraform-modules/aws/helm/helm_generic/variables.tf
[Latest commit](df092b633b61d364b8fc68d399fe972a5722f299) introduced the following behavior when using the module without supplied set, set_sensitive, or postrender inputs. 
PR would remove these as arguments until default implementation can be revisited
```
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 30, in resource "helm_release" "helm_chart":
│   30:   set                        = var.set
│ 
│ An argument named "set" is not expected here. Did you mean to define a
│ block of type "set"?
╵
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 31, in resource "helm_release" "helm_chart":
│   31:   set_sensitive              = var.set_sensitive
│ 
│ An argument named "set_sensitive" is not expected here. Did you mean to
│ define a block of type "set_sensitive"?
╵
╷
│ Error: …
```
=> patch helm_generic -set,set_sensitive,postrender

terraform-modules/aws/airflow/README.md, terraform-modules/aws/airflow/main.tf, terraform-modules/aws/airflow/variables.tf
- Apache Airflow configuration options can be attached to your Amazon Managed Workflows for Apache Airflow environment as environment variables
- Our airflow module didn't has this input variable
- Now is available to use
```
~ resource "aws_mwaa_environment" "this" {
~ airflow_configuration_options   = (sensitive value)
id                              = "dp-dev-airflow"
name                            = "dp-dev-airflow"
tags                            = {
"ops_env"              = "dp-dev"
"ops_managed_by"       = "terraform"
"ops_owners"           = "devops"
"ops_source_repo"      = "gruntwork-infrastructure-live"
"ops_source_repo_path" = "dp-dev/us-west-2/dp-dev/dataplatform/0300-airflow"
}
}
```
- Code where I am using this branch? …
=> Airflow variables configuration

terraform-modules/aws/ec2-tag/README.md, terraform-modules/aws/ec2-tag/main.tf, terraform-modules/aws/ec2-tag/output.tf, terraform-modules/aws/ec2-tag/variables.tf
- It collects information about running instances in the AWS (Amazon Web Services) cloud.
- It retrieves the identity of the AWS account that is executing the code.
- It creates a local variable called "instance_tags" that contains information about the instances and their associated tags.
- It applies the AWS EC2 tag to each instance based on the collected information.
=> Terraform for EC2 Tagging

terraform-modules/aws/s3/folders/README.md, terraform-modules/aws/s3/folders/main.tf, terraform-modules/aws/s3/folders/variables.tf
A simple module to create folders in an s3 bucket 
```
inputs = {
bucket_name = "${local.aws_region}-${local.account_id}-dp-dev-poc-sftp-data"
folder_structure = templatefile("./folder_structure.json", {})
}
folder_structure.json
[
"aaziz@exactpay.com",
"aaziz@exactpay.com/640a465cd2f4b9576e8b9b79",
"aaziz@exactpay.com/63c71e961c35406430780ead",
"640a465cd2f4b9576e8b9b79",
"63c71e961c35406430780ead"
]
```
```
+ resource "aws_s3_object" "directory_structure" {
+ acl                    = (known after apply)
+ bucket                 = "us-west-2-042093043970-dp-dev-poc-sftp-data"
+ bucket_key_enabled     = (known after apply)
+ content_type           = "application/x-directory"
+ etag                   = (known after apply)
+ force_destroy …
```
=> s3 folders structure

terraform-modules/aws/cluster-autoscaler/main.tf, terraform-modules/aws/cluster-autoscaler/variables.tf, terraform-modules/aws/helm/kube-prometheus-stack/main.tf, terraform-modules/aws/helm/kube-prometheus-stack/variables.tf
Fixing incorrect usage of the `version` var.  It can NOT be parameterized.
=> aws-parameterization-2

terraform-modules/aws/msk_1.0.9/main.tf, terraform-modules/aws/msk_1.0.9/variables.tf
- Adding 2 of new env vars to control if you want to create security group by own.
Where We are using this ?
https://github.com/exact-payments/gruntwork-infrastructure-live/pull/2007/files#diff-3e84ea31afb4f168a3ab0b0bf716e9e6109f1f31491a3c6b37fec378db7dc901R19
=> Msk feature 2

terraform-modules/aws/eks/main.tf, terraform-modules/aws/eks/variables.tf
- We want to be able to set add-ons.
- The current terraform has an add on fixed , in eks you need to fix some resources like kube-config, kube-proxy. 
- We are handle the particular role for some add ons, which is based on aws requirements.
=> EKS-MULTI-ADDONS
